<a href="https://colab.research.google.com/github/ucfilho/marquesgabi_2020/blob/master/ANN_fotos_testa_variaveis_02_jan_30_2020.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
from sklearn.model_selection import train_test_split
import numpy as np
import cv2
import math
import pandas as pd
from sklearn.neural_network import MLPRegressor
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score 
from mpl_toolkits.mplot3d import Axes3D, axes3d
from sklearn.metrics import classification_report, confusion_matrix
import matplotlib.pyplot as plt
import matplotlib
%matplotlib inline

In [0]:
#@title Digite os parametros { run: "auto", vertical-output: true }
#@markdown Enter neurons hidden layer
N_Hidden=18  #@param {type:"number"}
#@markdown Activation function

Ativa='logistic'#@param ["tanh", "identity", "logistic","relu"] {allow-input: true}

In [0]:
# funcao normatiza dados
def Normatiza(x):
    strings=list(x)
    for i in strings:
        max_x=x[i].max()
        min_x=x[i].min()
        a=(max_x+min_x)/2
        b=(max_x-min_x)/2
        x[i]=(x[i]-a)/b
    return x

In [0]:
# funcao retorna os dados a forma original
def Original(x,x_old):
    strings=list(x)
    for i in strings:
        max_x=x_old[i].max()
        min_x=x_old[i].min()
        a=(max_x+min_x)/2
        b=(max_x-min_x)/2
        x[i]=x[i]*b+a
    return x

In [5]:
!wget http://ftp.feq.ufu.br/ubirajara/Fotos_Treina_ANN_dez_2019.csv
Transfere='Fotos_Treina_ANN_dez_2019.csv'

--2020-01-30 15:03:26--  http://ftp.feq.ufu.br/ubirajara/Fotos_Treina_ANN_dez_2019.csv
Resolving ftp.feq.ufu.br (ftp.feq.ufu.br)... 200.19.144.11
Connecting to ftp.feq.ufu.br (ftp.feq.ufu.br)|200.19.144.11|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 21508 (21K) [text/csv]
Saving to: ‘Fotos_Treina_ANN_dez_2019.csv.2’

Fotos_Treina_ANN_de 100%[===================>]  21.00K  30.2KB/s    in 0.7s    

2020-01-30 15:03:27 (30.2 KB/s) - ‘Fotos_Treina_ANN_dez_2019.csv.2’ saved [21508/21508]



In [6]:
!wget http://ftp.feq.ufu.br/ubirajara/New_Feature_Cor_ANN_jan_2020.csv
Transfere_Cor='New_Feature_Cor_ANN_jan_2020.csv'

--2020-01-30 15:03:28--  http://ftp.feq.ufu.br/ubirajara/New_Feature_Cor_ANN_jan_2020.csv
Resolving ftp.feq.ufu.br (ftp.feq.ufu.br)... 200.19.144.11
Connecting to ftp.feq.ufu.br (ftp.feq.ufu.br)|200.19.144.11|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1807 (1.8K) [text/csv]
Saving to: ‘New_Feature_Cor_ANN_jan_2020.csv.2’

New_Feature_Cor_ANN 100%[===================>]   1.76K  --.-KB/s    in 0s      

2020-01-30 15:03:29 (243 MB/s) - ‘New_Feature_Cor_ANN_jan_2020.csv.2’ saved [1807/1807]



In [0]:
df= pd.read_csv(Transfere) 
df_cor= pd.read_csv(Transfere_Cor) 

In [8]:
df['Color']=df_cor['Color']
print(df)

     Unnamed: 0    Type  no.peaks  ...       Mean         Sd   Color
0             0  buraco       4.0  ...  18.934430  21.464729  0.4125
1             1  buraco       2.0  ...   8.392858  10.178723  0.4100
2             2  buraco       2.0  ...  10.898776  14.800251  0.4225
3             3  buraco       4.0  ...  77.750603  45.762334  0.4825
4             4  buraco       6.0  ...   8.154355   8.389805  0.5300
..          ...     ...       ...  ...        ...        ...     ...
115          35   indef       5.0  ...  15.704080  13.003255  0.4100
116          36   indef       2.0  ...  17.636505  14.887942  0.4350
117          37   indef       7.0  ...   5.432188   2.764440  0.5050
118          38   indef       4.0  ...   1.475860   0.597342  0.5325
119          39   indef       4.0  ...   2.133803   1.007575  0.4600

[120 rows x 13 columns]


In [9]:
pd.set_option('display.max_columns', None)  
pd.set_option('display.expand_frame_repr', False)
pd.set_option('max_colwidth', -1)
print(df.columns)

Index(['Unnamed: 0', 'Type', 'no.peaks', 'Media_proem', 'area under',
       'Width_peaks', 'Width_peaks_max', 'Width_peaks_min', 'Median', 'Mode',
       'Mean', 'Sd', 'Color'],
      dtype='object')


In [0]:
df['Type'] = df['Type'].map({'buraco':1, 'grao':2, 'indef':3}) 

In [11]:
Colunms=['no.peaks', 'Media_proem', 'area under','Width_peaks',
         'Median', 'Mode',
         'Mean', 'Sd','Color']
#X=df.iloc[:,2:12]
#y=df.iloc[:,1].astype(int)
X=df[Colunms]
#y=df['Type'].astype(int)
y=df['Type']
print(y)

0      1
1      1
2      1
3      1
4      1
      ..
115    3
116    3
117    3
118    3
119    3
Name: Type, Length: 120, dtype: int64


In [12]:
print(df.head())

   Unnamed: 0  Type  no.peaks  Media_proem    area under  Width_peaks  Width_peaks_max  Width_peaks_min      Median      Mode       Mean         Sd   Color
0  0           1     4.0       51.384595    2993.276979   38.492219    100.229477       0.616279         4.664086    1.576266  18.934430  21.464729  0.4125
1  1           1     2.0       47.626771    1315.847022   28.334735    60.077800        1.577800         3.425990    1.186329  8.392858   10.178723  0.4100
2  2           1     2.0       47.249986    1709.811993   35.353698    104.468318       1.018112         5.813794    1.019165  10.898776  14.800251  0.4225
3  3           1     4.0       70.047513    12391.952111  87.710404    156.975006       1.441023         102.551759  6.722350  77.750603  45.762334  0.4825
4  4           1     6.0       42.730606    1288.159588   30.966763    132.500000       0.508409         5.192788    1.336058  8.154355   8.389805   0.5300


In [13]:

# separa os dados variaveis de entrada em normatizados e originais
X_OLD=[]
X_OLD=X.copy()
X=Normatiza(X)
#print(X)


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:8: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


In [0]:
# Train Test Split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, 
                                                    random_state=25)

In [0]:
# define a rede neural 
#N_Hidden=(18,18,18)


clf = MLPClassifier(solver='lbfgs',activation=Ativa,alpha=1e-5,
                    hidden_layer_sizes=N_Hidden,random_state=0)


In [16]:
# treina a rede neural
clf.fit(X_train, y_train)


/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:470: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)


MLPClassifier(activation='logistic', alpha=1e-05, batch_size='auto', beta_1=0.9,
              beta_2=0.999, early_stopping=False, epsilon=1e-08,
              hidden_layer_sizes=18, learning_rate='constant',
              learning_rate_init=0.001, max_fun=15000, max_iter=200,
              momentum=0.9, n_iter_no_change=10, nesterovs_momentum=True,
              power_t=0.5, random_state=0, shuffle=True, solver='lbfgs',
              tol=0.0001, validation_fraction=0.1, verbose=False,
              warm_start=False)

In [0]:
# usa a rede neural treina em calculos para treino e teste
y_calc_train=clf.predict(X_train)
y_pred=clf.predict(X_test)


In [18]:
# Evaluating the Algorithm
print(confusion_matrix(y_pred, y_test))
print(classification_report(y_pred, y_test))

[[3 0 0]
 [4 6 5]
 [1 2 3]]
              precision    recall  f1-score   support

           1       0.38      1.00      0.55         3
           2       0.75      0.40      0.52        15
           3       0.38      0.50      0.43         6

    accuracy                           0.50        24
   macro avg       0.50      0.63      0.50        24
weighted avg       0.61      0.50      0.50        24



In [19]:
'''
[[5 4 2]
 [2 1 1]
 [1 3 5]]
              precision    recall  f1-score   support

           1       0.62      0.45      0.53        11
           2       0.12      0.25      0.17         4
           3       0.62      0.56      0.59         9

    accuracy                           0.46        24
   macro avg       0.46      0.42      0.43        24
weighted avg       0.54      0.46      0.49        24
'''

'\n[[5 4 2]\n [2 1 1]\n [1 3 5]]\n              precision    recall  f1-score   support\n\n           1       0.62      0.45      0.53        11\n           2       0.12      0.25      0.17         4\n           3       0.62      0.56      0.59         9\n\n    accuracy                           0.46        24\n   macro avg       0.46      0.42      0.43        24\nweighted avg       0.54      0.46      0.49        24\n'

In [20]:
print(y_pred)

[2 3 2 1 1 2 2 2 3 3 3 2 2 3 2 2 3 1 2 2 2 2 2 2]
